name: Main CI

on: [push, pull_request]

env:
  PNPM_VERSION: 8.5.1
  NODE_VERSION: 18.x

jobs:
  format_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: |
            - recursive: false
              args: [--filter, "@ct/valita-validator", --frozen-lockfile, --prefer-offline]

      - name: Format check
        run: pnpm --filter @ct/valita-validator fmt:ci

  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install dependencies
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: |
            - recursive: false
              args: [--filter, "@ct/valita-validator", --frozen-lockfile, --prefer-offline]

      - name: Test
        run: pnpm --filter @ct/valita-validator test
        env:
          NODE_ENV: test

  type-check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}

      - name: Use Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: pnpm

      - name: Install TypeScript type checker dependencies
        uses: pnpm/action-setup@v2.2.4
        with:
          version: ${{ env.PNPM_VERSION }}
          run_install: |
            - recursive: false
              args: [--filter, "@ct/valita-validator", --frozen-lockfile, --prefer-offline, --ignore-scripts]

      - name: Type check
        run: pnpm --filter "@ct/valita-validator" tc

